{% set version = "0.730" %}

package:
  name: mypy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mypy/mypy-{{ version }}.tar.gz
  sha256: 42a78944e80770f21609f504ca6c8173f7768043205b5ac51c9144e057dcf879

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - mypy = mypy.__main__:console_entry
    - stubgen = mypy.stubgen:main
    - dmyp = mypy.dmypy.client:console_entry

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - mypy_extensions >=0.4.0,<0.5.0
    - typed-ast >=1.4.0,<1.5.0
    - psutil >=4.0
    - typing_extensions >=3.7.4

test:
  imports:
    - mypy
    - mypy.plugins
    - mypy.server
    - mypy.test
  commands:
    - mypy --help
    - stubgen --help
    - dmypy --help

about:
  home: http://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Optional static typing for Python
  description: |
    Add type annotations to your Python programs, and use mypy to type check
    them. Mypy is essentially a Python linter on steroids, and it can catch
    many programming errors by analyzing your program, withoutactually having
    to run it.  Mypy has a powerful type system with features such as type
    inference, gradual typing, generics and union types.
  doc_url: http://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
