{% set name = "mypy" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mypy-{{ version }}.tar.gz
  sha256: b031b9601f1060bf1281feab89697324726ba0c0bae9d7cd7ab4b690940f0b92

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  skip: true  # [py<38]
  entry_points:
    - mypy = mypy.__main__:console_entry
    - stubgen = mypy.stubgen:main
    - stubtest = mypy.stubtest:main
    - dmypy = mypy.dmypy.client:console_entry
    - mypyc = mypyc.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions >=4.1.0
    - mypy_extensions >=1.0.0
    - tomli >=1.1.0  # [py<311]
    # extra: dmypy
    - psutil >=4.0

test:
  imports:
    - mypy
    - mypy.dmypy
    - mypy.plugins
    - mypy.server
    - mypyc
  commands:
    - pip check
    - mypy --help
    - stubgen --help
    - stubtest --help
    - dmypy --help
    - mypyc --help
  requires:
    - pip

about:
  home: https://www.mypy-lang.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Optional static typing for Python
  description: |
    Add type annotations to your Python programs, and use mypy to type check
    them. Mypy is essentially a Python linter on steroids, and it can catch
    many programming errors by analyzing your program, withoutactually having
    to run it.  Mypy has a powerful type system with features such as type
    inference, gradual typing, generics and union types.
  doc_url: https://mypy.readthedocs.io
  dev_url: https://github.com/python/mypy

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
