# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J0j2yPIM9U6z3ZzusgvCmGzuVTP+LhhAyojMCOLaecpa0IfrWbHYZIRY3Pu/fFOZOX1Dnvho/U6xzI9CspqoD5EilpWsfWv1PKK3/k1c0YBMGUEmPP4lCxeZ1vXYOqZkyXDvN6p4fFBogusRuKogv5hcQiSuDfBF04rkaiOWlvO2LRc+ya8dNjfhKAFqFH6YwiTEaSJrYfjB+zqMCA1+RRNxg/lwmhCesyZS5UDuS2rODvOYPOxXLNwkgtxkxhRV0zSbEyuxKS/7RDZCIR0HIz4mFnYsZ8BbKHDt/pIiak37d/PvxK6QRdENYOi0Z2rT8AnslhDiCkmuvOzuDiTseU5RTZu9Ri3lwZSxg4uvK7izn6OjIBrAnFM5ME/OKFx8H1mLFw7OpUe3dAzhhANooAoVVuGW8RpezYFejbZ7+InpSSEgSiv4h4+6K6dMeINODBR400QOOKc/InZGVMpQL529EtLO291eWo5J2cGTIUTKdtg1sNLmfyOWG63aNhmHQLgaEasn45TYjhHahifO2rdwxObXVDve+wM67PayimpY3Pzw4DGnI3O507wwHikFRvtGdSMr6HwDctLWtDAy87kN8up3zjvlR1xEdQurXY/cc/Gx4FN89jtHLI5mtP/lwPFT7AkwaTIYGUoGsxY9MTKHvlUwFx7t3cPPu4TcHJE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
