appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: J0j2yPIM9U6z3ZzusgvCmGzuVTP+LhhAyojMCOLaecpa0IfrWbHYZIRY3Pu/fFOZOX1Dnvho/U6xzI9CspqoD5EilpWsfWv1PKK3/k1c0YBMGUEmPP4lCxeZ1vXYOqZkyXDvN6p4fFBogusRuKogv5hcQiSuDfBF04rkaiOWlvO2LRc+ya8dNjfhKAFqFH6YwiTEaSJrYfjB+zqMCA1+RRNxg/lwmhCesyZS5UDuS2rODvOYPOxXLNwkgtxkxhRV0zSbEyuxKS/7RDZCIR0HIz4mFnYsZ8BbKHDt/pIiak37d/PvxK6QRdENYOi0Z2rT8AnslhDiCkmuvOzuDiTseU5RTZu9Ri3lwZSxg4uvK7izn6OjIBrAnFM5ME/OKFx8H1mLFw7OpUe3dAzhhANooAoVVuGW8RpezYFejbZ7+InpSSEgSiv4h4+6K6dMeINODBR400QOOKc/InZGVMpQL529EtLO291eWo5J2cGTIUTKdtg1sNLmfyOWG63aNhmHQLgaEasn45TYjhHahifO2rdwxObXVDve+wM67PayimpY3Pzw4DGnI3O507wwHikFRvtGdSMr6HwDctLWtDAy87kN8up3zjvlR1xEdQurXY/cc/Gx4FN89jtHLI5mtP/lwPFT7AkwaTIYGUoGsxY9MTKHvlUwFx7t3cPPu4TcHJE=}
