travis:
  secure:
    BINSTAR_TOKEN: UdH9O7Zn6AkZ6yvPHzanvJMZAhozpVNxzYloU7i2i99+NEZmHwdwLlImauXZB/uS98npmR5czZ4AgNa6whfDwhw9VaKSuIqJyET/AF9NYbxPZtW5CmH06rLhS/tw6BIM+oI9CzD9d+DmlBfb1ETbKeRiBD3wcgf/ok/v2tFeWvvz33MFr0ICKsx5w2tyHh77+pasAQ0aqQFOAujZN8XQmt2yQUnXYDIE7zj2s0qCjNuIjJk/09c6e8U5QUJ91Tn+GrafdH8VvrT/c6Aghls6P2Z774rL0VKWChfA1wxSoQb6zXSh5r/GiPdugoqG/mq+rn3PWVeD7bWuCWLIOSi+h7lza5asAxSu3nYKYEMZ5TCCYDi4AZkB2UhcVndf5kWXqiSoiJvNj00ClyunXoUR3FaFYBbKdK9P7XfZ0Y5v8QYBu03ZR7TMCX9yxZuFixYpHlYIw3h4M5h9TMZaJWmXZvQjHIZp5SCcPnxYVioG4P7Ktm0K9zgRfo9dPBIEzzODHHF3BJkvxLrwIYxHhC/X1HKk5lJBcyNohqJmSTXkD6Wluf2Qrto6MC/NUwSkeWR0S7CmlgDP1oGvK3vqOlEv+yNJv6SqnQxXvFNt8V+XqwqMspjd8fO7jusVXbmoOf5XoZh5zKu0hAfyEF+ytJKiSLzNIWmXqWw5mNolShK2Mrw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
